import { IconType } from 'react-icons';
import {
  GiDramaMasks,
  GiPistolGun,
  GiMachineGunMagazine,
  GiRailRoad,
  GiWorld,
  GiFootsteps,
  GiDrippingKnife,
  GiHammerSickle,
  GiTank,
  GiStaryu,
  GiIonicColumn,
  GiBatMask,
  GiCometSpark,
  GiOakLeaf,
  GiMoebiusTriangle,
  GiManacles,
  GiWesternHat,
  GiMusicalNotes,
} from 'react-icons/gi';
import { BsEmojiSmile } from 'react-icons/bs';
import { FaHatWizard, FaFeatherAlt } from 'react-icons/fa';
import { FiHeart } from 'react-icons/fi';
import { RiAliensLine } from 'react-icons/ri';
import { MdFamilyRestroom, MdSportsHandball } from 'react-icons/md';

export enum Genres {
  drama = 'Драмы',
  comedy = 'Комедии',
  boeviki = 'Боевики',
  thriller = 'Триллеры',
  adventures = 'Приключения',
  foreign = 'Зарубежные',
  melodramy = 'Мелодрамы',
  fantastika = 'Фантастика',
  fantasy = 'Фентези',
  dlya_vsei_semi = 'Семейные',
  detective = 'Детективы',
  horror = 'Ужасы',
  sovetskoe_kino = 'Советские',
  voennye = 'Военные',
  rossijskie = 'Русские',
  istoricheskie = 'Исторические',
  detskiy = 'Для детей',
  comics = 'По комиксам',
  disaster = 'Катастрофы',
  arthouse = 'Артхаус',
  misticheskie = 'Мистические',
  crime = 'Криминал',
  sport = 'Спорт',
  biography = 'Биография',
  western = 'Вестерн',
  music = 'Музыкальные',
}

export const genresIcons: { genre: string; icon: IconType }[] = [
  { genre: 'Драмы', icon: GiDramaMasks },
  { genre: 'Комедии', icon: BsEmojiSmile },
  { genre: 'Боевики', icon: GiPistolGun },
  { genre: 'Триллеры', icon: GiMachineGunMagazine },
  { genre: 'Приключения', icon: GiRailRoad },
  { genre: 'Зарубежные', icon: GiWorld },
  { genre: 'Мелодрамы', icon: FiHeart },
  { genre: 'Фантастика', icon: RiAliensLine },
  { genre: 'Фентези', icon: FaHatWizard },
  { genre: 'Семейные', icon: MdFamilyRestroom },
  { genre: 'Детективы', icon: GiFootsteps },
  { genre: 'Ужасы', icon: GiDrippingKnife },
  { genre: 'Советские', icon: GiHammerSickle },
  { genre: 'Военные', icon: GiTank },
  { genre: 'Русские', icon: GiStaryu },
  { genre: 'Исторические', icon: GiIonicColumn },
  { genre: 'Для детей', icon: GiDramaMasks },
  { genre: 'По комиксам', icon: GiBatMask },
  { genre: 'Катастрофы', icon: GiCometSpark },
  { genre: 'Артхаус', icon: GiOakLeaf },
  { genre: 'Мистические', icon: GiMoebiusTriangle },
  { genre: 'Криминал', icon: GiManacles },
  { genre: 'Спорт', icon: MdSportsHandball },
  { genre: 'Биография', icon: FaFeatherAlt },
  { genre: 'Вестерн', icon: GiWesternHat },
  { genre: 'Музыкальные', icon: GiMusicalNotes },
];
