export const description = [
  'firstParahraph',
  'secondParagraph',
  'listHeading',
  'headInfo',
  'firstListItem',
  'secondListItem',
  'thirdListItem',
  'fourthListItem',
  'fifthListItem',
  'sixthListItem',
  'seventhListItem',
  'eighthListItem',
  'lastParagraph',
];